name: misuralegno
recipe: wordpress
proxy:
  # pma:
    # - pma.starter.lndo.site
  mailhog:
    - mailhog.misuralegno.lndo.site
config:
  webroot: .
  via: apache
  php: "8.2"
  xdebug: true
services:
  mailhog:
    type: mailhog
  # pma:
  #   type: phpmyadmin
  #   host:
  #     - database
      
